package com.example.realmproject;

import android.content.Context;
import android.graphics.Color;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.TextView;

import androidx.annotation.NonNull;
import androidx.recyclerview.widget.RecyclerView;
import io.realm.RealmResults;

//MyViewHolder is a class that extends RecyclerView.ViewHolder

public class MyAdapter extends RecyclerView.Adapter<MyAdapter.MyViewHolder> {  //onCreateViewHolder getItemCount onBindViewHolder is autogenerated or Imported Methods

    private RealmResults<MyPerson> myPersonRealmResults;
    private Context context;
    private final String TAG="Experiment";
    private int count;
    private ImageView img_view;
    private String[] colors={"#4287f5","#4bf542","#f5f242","#e32424"};
    MyAdapter(RealmResults<MyPerson> persons,Context con) {  //have to create by own
        myPersonRealmResults = persons;
        context = con;
        count = 0;
    }

    @NonNull
    @Override
    public MyViewHolder onCreateViewHolder(@NonNull ViewGroup parent, int viewType) {
        View view= LayoutInflater.from(parent.getContext()).inflate(R.layout.recyclerview,parent,false); //recyclerview is the xml file of the Recyclerview
        return new MyViewHolder(view);
    }

    @Override
    public void onBindViewHolder(@NonNull MyViewHolder holder, int position) {
        img_view=holder.itemView.findViewById(R.id.img_view);
        Log.i(TAG, "onBindViewHolder: Triggered");
         MyPerson myPerson=myPersonRealmResults.get(position);
         holder.name.setText(myPerson.getName());
         holder.dept.setText("Department :"+myPerson.getDept());
         holder.roll.setText("ROLL :"+String.valueOf(myPerson.getRoll()));
         holder.phone.setText("PH NO :+91 "+myPerson.getPhone());
         holder.gender.setText(myPerson.getGender());
         if(myPerson.getGender().toString().equals("Male"))
            img_view.setImageResource(R.drawable.avatar_male);
         else
             img_view.setImageResource(R.drawable.avatar_girl);
         holder.itemView.findViewById(R.id.category_image).setBackgroundColor(Color.parseColor(colors[position%4]));
    }

    @Override
    public int getItemCount() {
        return myPersonRealmResults.size();
    }

    public class MyViewHolder extends RecyclerView.ViewHolder {
        private TextView name;
        private TextView dept;
        private TextView roll;
        private TextView phone;
        private TextView gender;
        public MyViewHolder(@NonNull View itemView) {
            super(itemView);
            count++;
            name=itemView.findViewById(R.id.name_tv);
            dept=itemView.findViewById(R.id.dept_tv);
            roll=itemView.findViewById(R.id.rollno_tv);
            phone=itemView.findViewById(R.id.phone_tv);
            gender=itemView.findViewById(R.id.gender_tv);
        }

    }
}
